require.config({
	baseUrl:"/",
	paths:{
		jquery:"lib/jquery/jquery-1.12.4.min",
		cookie:"lib/jquery_plugins/jquery.cookie",
		zoom:"lib/jquery_plugins/jquery.elevateZoom-3.0.8.min",//放大镜插件
		carousel:"lib/jquery_plugins/jquery.xmcarousel",//轮播图
		template:"lib/artTemplate/template"//模块

	},
	shim:{
		carousel:{
			deps:["jquery"]
		}
		zoom:{
			deps:["jquery"]
		}
	}
});